pnpm with lerna update
equinor/fusion-react-components pull request #967
Opened 2023-08-31 08:01 UTC by AndrejNikolicEq

# pnpm with lerna 7.2 update

### Type
- Maintenance (deps only)

### Reference to assignment

2023-08-31 08:02 UTC, AndrejNikolicEq commented
still WIP, added for testing pnpm in workflow

2023-09-01 07:34 UTC, eikeland approved these changes

2023-09-01 09:07 UTC, AndrejNikolicEq commented
Complete

2023-09-01 11:57 UTC, AndrejNikolicEq commented
added changeset

2023-09-04 06:50 UTC, odinr commented on package.json
> +    "clean": "rm -rf node_modules && rm -rf pnpm-lock.yaml && lerna clean -y",
this should be using rimraf so it will be MS comp

2023-09-05 12:31 UTC, odinr commented on .github/workflows/chromatic.yml
> +
nope!
use the correct action, which should be executed before npm install, for caching pnpm modules

2023-09-05 12:31 UTC, odinr commented on .github/workflows/generate-docs.yml
> +        run: npm install pnpm -g
see previous commnent about pnpm init

2023-09-05 12:32 UTC, odinr commented on .github/workflows/lint.yml
> +        run: npm install pnpm -g
see above

2023-09-05 12:32 UTC, odinr commented on .github/workflows/pre-release.yml
> +        run: npm install pnpm -g
see above

2023-09-05 12:32 UTC, odinr commented on .github/workflows/pre-release.yml
> +          GH_TOKEN: ${{ github.token }}
Nope, read docs

2023-09-05 12:33 UTC, odinr requested changes
we need to talk before this is merged

2023-09-11 11:44 UTC, AndrejNikolicEq commented on .github/workflows/pre-release.yml
> +          GH_TOKEN: ${{ github.token }}
where? looks ok here https://github.com/changesets/changesets/blob/main/docs/prereleases.md

2023-09-19 07:17 UTC, odinr commented on .github/workflows/pre-release.yml
> +          pnpm changeset pre enter next
read about [pre release](https://github.com/changesets/changesets/blob/main/docs/prereleases.md)
this is to advance to use within a pipeline, use [snapshot](https://github.com/changesets/changesets/blob/main/docs/snapshot-releases.md)

2023-09-19 07:18 UTC, odinr commented on .github/workflows/pre-release.yml
> +            git commit -m'chore(prerelease): enter prerelease mode and version packages with tag ${{ github.event.inputs.tag }}'
this wont work

2023-09-19 07:19 UTC, odinr commented on .github/workflows/pre-release.yml
> +        run: |
no, read the documentation, we do NOT want to release a pre-release as latests

2023-09-19 07:20 UTC, odinr commented on CONTRIBUTING.md
> +npm install pnpm -g
should reference to PNPM doc side

2023-09-19 07:59 UTC, odinr commented on packages/filter/src/FilterProvider.tsx
> +export const FilterProvider: <
why is this file modified in this PR

2023-09-19 08:00 UTC, odinr commented on packages/filter/src/components/filter/checkbox/CheckboxFilterProvider.tsx
> +    (data: TData[], selection: Set<TValue>) => {
why is this file modified in this PR

2023-09-19 08:00 UTC, odinr commented on packages/filter/src/components/panel/FilterPanel.tsx
> +export const FilterPanel: <TData>(props: React.PropsWithChildren<FilterPanelProps<TData>>) => JSX.Element = <TData,>(
Why is iths file in this PR

2023-09-19 08:00 UTC, odinr commented on packages/filter/src/components/panel/FilterPanelProvider.tsx
> +const { Provider, Consumer } = context as { Provider: any; Consumer: any };
Why is iths file in this PR

2023-09-19 08:00 UTC, odinr commented on packages/filter/src/context.ts
> +export const { Provider, Consumer } = context as { Provider: any; Consumer: any };
Why is iths file in this PR

2023-09-19 08:00 UTC, odinr commented on packages/filter/src/options/FilterOptionProvider.tsx
> +export const FilterOptionProvider: <TData extends Record<string, any>, TOption extends FilterOption, TValue>(
Why is iths file in this PR

2023-09-19 08:00 UTC, odinr commented on packages/filter/src/options/context.ts
> +
Why is iths file in this PR

2023-09-19 08:00 UTC, odinr commented on packages/hanging-garden/src/components/PopoverContainer/index.tsx
> +const PopoverContainer: React.ForwardRefExoticComponent<
Why is iths file in this PR

2023-09-19 08:01 UTC, odinr commented on packages/hanging-garden/src/renderHooks/useHangingGardenContext.tsx
> +const HangingGardenContext: React.Context<IHangingGardenContext> = createContext<IHangingGardenContext>(
Why is iths file in this PR

2023-09-19 08:02 UTC, odinr commented on packages/side-sheet/package.json
> +    "typescript": "^4.4.4"
why is typescript downgraded?

2023-09-19 08:06 UTC, odinr requested changes
this PR contains 49 commits, maybe rebase since this is a major change
this PR includes changes to files which are not affected by the move to PNPM
some of the workflows would not run, or ruin released packages

2023-10-04 07:40 UTC, odinr submitted a review, later dismissed

2023-10-05 05:46 UTC, merged